<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/example/example.proto

namespace GPBMetadata\Protos\Example;

class Example
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            '
Š
protos/example/example.protoExample"¯
ExampleMessage
name (	

id (
email (	0
last_updated (2.google.protobuf.Timestamp
surname (	1
date_of_birth (2.google.protobuf.TimestampB\'Z/pb/exampleª
Pb.ExampleÊ
Pb\\Examplebproto3'
        , true);

        static::$is_initialized = true;
    }
}

