<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/example/example.proto

namespace Pb\Example;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Example.ExampleMessage</code>
 */
class ExampleMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>int32 id = 2;</code>
     */
    protected $id = 0;
    /**
     * Generated from protobuf field <code>string email = 3;</code>
     */
    protected $email = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_updated = 4;</code>
     */
    protected $last_updated = null;
    /**
     * Generated from protobuf field <code>string surname = 5;</code>
     */
    protected $surname = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_of_birth = 6;</code>
     */
    protected $date_of_birth = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type int $id
     *     @type string $email
     *     @type \Google\Protobuf\Timestamp $last_updated
     *     @type string $surname
     *     @type \Google\Protobuf\Timestamp $date_of_birth
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Protos\Example\Example::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 id = 2;</code>
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>int32 id = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string email = 3;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Generated from protobuf field <code>string email = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_updated = 4;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getLastUpdated()
    {
        return $this->last_updated;
    }

    public function hasLastUpdated()
    {
        return isset($this->last_updated);
    }

    public function clearLastUpdated()
    {
        unset($this->last_updated);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_updated = 4;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setLastUpdated($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->last_updated = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string surname = 5;</code>
     * @return string
     */
    public function getSurname()
    {
        return $this->surname;
    }

    /**
     * Generated from protobuf field <code>string surname = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setSurname($var)
    {
        GPBUtil::checkString($var, True);
        $this->surname = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_of_birth = 6;</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getDateOfBirth()
    {
        return $this->date_of_birth;
    }

    public function hasDateOfBirth()
    {
        return isset($this->date_of_birth);
    }

    public function clearDateOfBirth()
    {
        unset($this->date_of_birth);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp date_of_birth = 6;</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setDateOfBirth($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->date_of_birth = $var;

        return $this;
    }

}

