<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/example/example.proto

namespace Pb\Example;

if (false) {
    /**
     * This class is deprecated. Use Pb\Example\ExampleMessage\Gender instead.
     * @deprecated
     */
    class ExampleMessage_Gender {}
}
class_exists(ExampleMessage\Gender::class);
@trigger_error('Pb\Example\ExampleMessage_Gender is deprecated and will be removed in the next major release. Use Pb\Example\ExampleMessage\Gender instead', E_USER_DEPRECATED);

