<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/contacts/person.proto

namespace Contacts;

if (false) {
    /**
     * This class is deprecated. Use Contacts\Person\PhoneType instead.
     * @deprecated
     */
    class Person_PhoneType {}
}
class_exists(Person\PhoneType::class);
@trigger_error('Contacts\Person_PhoneType is deprecated and will be removed in the next major release. Use Contacts\Person\PhoneType instead', E_USER_DEPRECATED);

