<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/contacts/person.proto

namespace Pb\Contacts;

if (false) {
    /**
     * This class is deprecated. Use Pb\Contacts\Person\PhoneNumber instead.
     * @deprecated
     */
    class Person_PhoneNumber {}
}
class_exists(Person\PhoneNumber::class);
@trigger_error('Pb\Contacts\Person_PhoneNumber is deprecated and will be removed in the next major release. Use Pb\Contacts\Person\PhoneNumber instead', E_USER_DEPRECATED);

